micronaut:
  application:
    name: pix

grpc:
  port: ${SERVER_PORT:50051}
  keep-alive-time: 1h
  max-inbound-message-size: 1024

datasources:
  default:
    url: jdbc:mysql://localhost:3306/pix
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: masterkey
    schema-generate: CREATE_DROP
    dialect: MYSQL
jpa.default.properties.hibernate.hbm2ddl.auto: update

itau:
  contas:
    url: http://localhost:9091